services:
  scanner:
    build: ./scanner
    container_name: secrets-scanner
    ports:
      - "8001:8001"
    networks:
      - secrets-net

  llm-analysis:
    build: ./llm-analysis
    container_name: secrets-llm-analysis
    ports:
      - "8002:8002"
    environment:
      - GEMENI_API_KEY=AIzaSyC5aNSgldoPDynfQEHji_0pSh80R6xdlUk
    networks:
      - secrets-net

  orchestrator:
    build: ./orchestrator
    container_name: secrets-orchestrator
    ports:
      - "8000:8000"
    environment:
      - SCANNER_URL=http://scanner:8001
      - LLM_ANALYSIS_URL=http://llm-analysis:8002
    volumes:
      - ./test-repos:/repos:ro
    depends_on:
      - scanner
      - llm-analysis
    networks:
      - secrets-net

  frontend:
    build: ./frontend
    container_name: secrets-ui
    ports:
      - "3000:80"
    depends_on:
      - orchestrator
    networks:
      - secrets-net


networks:
  secrets-net:
    driver: bridge
